### ISSUE TITLE
ROOT_LOGIN=yes , still disable root login

### ISSUE THREAD

**Issue by ghprod** [Mins/TuxLite#49]
HI, 

i've set `ROOT_LOGIN=yes` in options.conf but in the end of installation, still give me notice that root login has disabled and we need to `adduser`

how to fix this?

thanks

**Comment by siparker** [comment]
debian 7 here. finishes with root login disabled
Installation complete!
Root login disabled.

it is set to yes in config

**Comment by djvdorp** [comment]
Seems this was fixed here: #51 (basically the message was wrong)
