### ISSUE TITLE
different 14.04 kernel seems to cause issues

### ISSUE THREAD

**Issue by siparker** [Mins/TuxLite#54]
i have used this script successfully on 14.04.2 LTS (GNU/Linux 2.6.32-042stab103.6 x86_64)
setup all ran fine no issues
It however doesnt work with GNU/Linux 3.10.23-xxxx-std-ipv6-64-vps x86_64

not sure what the difference is but the script fails on this kernel

I used a different OVH cloud VPS and after it removes bind9 it can no longer resolve any of the ubuntu repositories.
as such it processes and says completed at each stage but does not install anything as it has err cannot resolve security.ubuntu.com or archive. or any other repo's

the errors begin after bind9 is removed
apache2: unrecognized service
sendmail: unrecognized service
- Stopping domain name service... bind9                                                                      waiting for pid 4036 to die
                                                                                                     [ OK ]
  nscd: unrecognized service
  The following packages will be REMOVED:
  bind9{p}
  0 packages upgraded, 0 newly installed, 1 to remove and 2 not upgraded.
  Need to get 0 B of archives. After unpacking 942 kB will be freed.
  (Reading database ... 33380 files and directories currently installed.)
  Removing bind9 ...
  rm '/etc/systemd/system/multi-user.target.wants/bind9.service'
  Purging configuration files for bind9 ...
  Deleting bind user
  dpkg: warning: while removing bind9, directory '/var/cache/bind' not empty so not removed
  Processing triggers for ureadahead ...
  Processing triggers for ufw ...
  Processing triggers for man-db ...

Configuring /etc/apt/sources.list.
Enabling MariaDB.org repo for Ubuntu saucy.
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.csbXrMv8n9 --trustdb-name /etc/apt//trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db
gpg: requesting key 1BB943DB from hkp server keyserver.ubuntu.com
?: keyserver.ubuntu.com: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection refused
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
Err http://archive.ubuntu.com saucy InRelease
Err http://archive.ubuntu.com saucy-updates InRelease
Err http://security.ubuntu.com saucy-security InRelease
Err http://ftp.osuosl.org saucy InRelease
Err http://ftp.osuosl.org saucy Release.gpg
  Could not resolve 'ftp.osuosl.org'
Err http://archive.ubuntu.com saucy Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://security.ubuntu.com saucy-security Release.gpg
  Could not resolve 'security.ubuntu.com'
Err http://archive.ubuntu.com saucy-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/saucy/InRelease:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/saucy-updates/InRelease:
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/saucy-security/InRelease:
W: Failed to fetch http://ftp.osuosl.org/pub/mariadb/repo/5.5/ubuntu/dists/saucy/InRelease:
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/saucy/Release.gpg: Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/saucy-updates/Release.gpg: Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/saucy-security/Release.gpg: Could not resolve 'security.ubuntu.com'
W: Failed to fetch http://ftp.osuosl.org/pub/mariadb/repo/5.5/ubuntu/dists/saucy/Release.gpg: Could not resolve 'ftp.osuosl.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.

It basically replicates this for all future requests for packages and then finished with

 Generating self signed SSL cert...
The following NEW packages will be installed:
  expect tcl8.5{a} tcl8.5-lib{a}
0 packages upgraded, 3 newly installed, 0 to remove and 2 not upgraded.
Need to get 1,268 kB of archives. After unpacking 4,072 kB will be used.
Err http://archive.ubuntu.com/ubuntu/ saucy/main tcl8.5-lib amd64 8.5.13-1ubuntu4
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ saucy/main tcl8.5 amd64 8.5.13-1ubuntu4
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com/ubuntu/ saucy/main expect amd64 5.45-3
  Could not resolve 'archive.ubuntu.com'
0% [Working]E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/t/tcl8.5/tcl8.5-lib_8.5.13-1ubuntu4_amd64.deb: Could not resolve 'archive.ubuntu.com'

./setup.sh: line 417: expect: command not found

No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.

nginx: unrecognized service
php5-fpm: unrecognized service
php5-fpm: unrecognized service
 Optimize complete!

Installation complete!
Root login disabled.

This is also even though i set root login to yes in options.conf also

I suppose there are several issues with the new 14.04 kernel / process here.

however. if you use the OVH classic VPS instead of the Cloud VPS then you get ubuntu 14.04 with the

**Comment by djvdorp** [comment]
> I used a different OVH cloud VPS and after it removes bind9 it can no longer resolve any of the ubuntu repositories.

Looks like your OVH Cloud VPS requires bind9 running inside the VPS to have functioning networking, this is not something the script can resolve for you unfortunately. Have never seen this before myself.
