### ISSUE TITLE
Awstats - You don't have permission to access /stats/ on this server

### ISSUE THREAD

**Issue by codeeditor** [Mins/TuxLite#55]
Server: Debian Wheezy, Apache, MySQL, Awstats = on

After running command:
./domain.sh stats on
Awstats are not accessible on domainname.com/stats/ with error:
You don't have permission to access /stats/ on this server.
Additional configuration is required?
Best regards

**Comment by djvdorp** [comment]
Closing as Wheezy is end-of-life.
