### ISSUE TITLE
phpMyAdmin downloar url changed

### ISSUE THREAD

**Issue by ilosh** [Mins/TuxLite#61]
Hi,
the phpMyAdmin download url has changed. It is not available at sourceforge anymore. When using ./setup.sh dbgui it gives an error because phpMyAdmin could not be downloaded.

New url:
https://files.phpmyadmin.net/phpMyAdmin/${PMA_VER}/phpMyAdmin-${PMA_VER}-all-languages.tar.gz

**Comment by danrebelz** [comment]
Thanks for the new url. But where do I change download url?

**Comment by djradivip** [comment]
In setup.sh.
Look for function install_dbgui .

**Comment by djvdorp** [comment]
Fixed in commit https://github.com/Mins/TuxLite/commit/d38dea7da2b7b9614ce684ffcec45a6d0f7f8925.
