### ISSUE TITLE
select APACHE but NGINX still installs

### ISSUE THREAD

**Issue by Choppra** [Mins/TuxLite#67]
Test it multiple times and it seems to be the case

**Comment by Choppra** [comment]
Hello?  is this thing on?

**Comment by baoang** [comment]
My guess is that the script installs both apache and nginx. 

It could be much appreciated that three options were provided, apache install, nginx install, and apache+nginx insall.

**Comment by djvdorp** [comment]
Need to investigate this further.

**Comment by djvdorp** [comment]
I was unable to reproduce this with `WEBSERVER=2` on Ubuntu 14.04, only `apache2` did get installed.
If you are still facing this issue, could you create a new issue with more details on the environment?
